### PR TITLE
Used OpenSCAD to hack together an adjustment for the incorrect spacing on the North America version

### PR DESCRIPTION
**Pull request by scates**

### CODE REVIEW

**Comment by Cederb** [comment]
To be honest, the main problem is that North american hole punches varies wildly, with differing holes sizes and tolerances all over the places.

**Comment by scates** [comment]
Sure, but as far as I can tell, the positioning is fairly consistent.  The holes are meant to be 4.5 inches (108 mm) apart, and I haven't used any hole punches that are far off from that.  Certainly not 2mm off.

I don't actually expect you to merge in this pull request; I just wanted to make it more visible for anyone else who might benefit from my hacky workaround.  If you can adjust the positions in the original, then I'll just close this request.

**Comment by Cederb** [comment]
I actually moved them back since people in NA complained about a lack of tension and the sheet coming off when the arms spread, this is why i am a bit reluctant to doing a large change like moving it 2mm forward like you are suggesting. Also consider that the distance decreases a bit when you put it on your head and the arms flex outwards.

Yesterday, i even got the request to move the hooks back another mm because they did not think the tension was enough.

The spacing is btw not the largest problem, but that it is common to have holes that are down to just under 6mm up to over 8mm in size, creating more than 2mm difference just because of different punch sizes.

**Comment by Cederb** [comment]
I will cut out some test sheets on the makerspace laser cutter tonight and try to see for myself what should be the best distance, and modifiy it according to that.

**Comment by scates** [comment]
Oh, I see what you mean about the hole size impacting the tension. Yeah, that is really annoying.

Leave it to North America to screw up standards.

**Pull request closed without merging**
